nextcloud/android-common

- .github/dependabot.yml
- .github/workflows/assemble.yml
rel #4 
- Add dependabot config
- Add simple assemble workflow
> Some basic CI stuff

- .github/workflows/check.yml
- build.gradle
- scripts/hooks/pre-commit
- ui/src/main/java/com/nextcloud/android/common/ui/theme/ViewThemeUtilsBase.kt
- ui/src/main/java/com/nextcloud/android/common/ui/theme/utils/AndroidViewThemeUtils.kt
- build: add Spotless with configs for Kotlin
- Add detekt plugin with default config
- Fix detekt problems
- Add workflow to check detekt, ktlint and lint
- Add pre-commit hook to run ktlint, detekt and lint
> Add detekt, ktlint, hooks and check workflow

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
> Bump AGP to 7.3

- ui/src/main/java/com/nextcloud/android/common/ui/color/ColorUtil.kt
Seen in Google Play crash reports
> ui: ColorUtil: handle invalid colors in parseColorOrFallback

- material-color-utilities/build.gradle
- material-color-utilities/src/main/java/contrast/Contrast.java
- material-color-utilities/src/main/java/dislike/DislikeAnalyzer.java
- material-color-utilities/src/main/java/dynamiccolor/DynamicColor.java
- material-color-utilities/src/main/java/dynamiccolor/ToneDeltaConstraint.java
- material-color-utilities/src/main/java/dynamiccolor/TonePolarity.java
- material-color-utilities/src/main/java/hct/Cam16.java
- material-color-utilities/src/main/java/hct/Hct.java
- material-color-utilities/src/main/java/hct/ViewingConditions.java
- material-color-utilities/src/main/java/palettes/TonalPalette.java
- material-color-utilities/src/main/java/quantize/QuantizerMap.java
- material-color-utilities/src/main/java/quantize/QuantizerWsmeans.java
- material-color-utilities/src/main/java/quantize/QuantizerWu.java
- material-color-utilities/src/main/java/scheme/DynamicScheme.java
- material-color-utilities/src/main/java/scheme/SchemeExpressive.java
- material-color-utilities/src/main/java/scheme/SchemeFidelity.java
- material-color-utilities/src/main/java/scheme/SchemeMonochrome.java
- material-color-utilities/src/main/java/scheme/SchemeNeutral.java
- material-color-utilities/src/main/java/scheme/SchemeTonalSpot.java
- material-color-utilities/src/main/java/scheme/SchemeVibrant.java
- material-color-utilities/src/main/java/scheme/Variant.java
- material-color-utilities/src/main/java/temperature/TemperatureCache.java
- material-color-utilities/src/main/java/utils/ColorUtils.java
see https://github.com/material-foundation/material-color-utilities/commits/main
tested against latest android-talk master using https://jitpack.io/com/github/nextcloud/android-common/222879ef38/build.log
Signed-off-by: Andy Scherzinger <info@andy-scherzinger.de>
> Update material color code to latest version: 14th Dec 2022, 6:39 PM GMT+1

- material-color-utilities/src/main/java/dynamiccolor/DynamicColor.java
- material-color-utilities/src/main/java/scheme/SchemeContent.java
- material-color-utilities/src/main/java/scheme/Variant.java
> Update color utils to latest master 22nd March 2023

- core/build.gradle
- ui/build.gradle
- ui/src/main/java/com/nextcloud/android/common/ui/theme/utils/AndroidViewThemeUtils.kt
> Bump dependency versions and sdk targets to latest

- ui/src/main/java/com/nextcloud/android/common/ui/theme/utils/MaterialViewThemeUtils.kt
> Theme overflow menu icon when theming the toolbar

- .github/workflows/assemble.yml
- .github/workflows/check.yml
... to pin them correctly _an_ be able to check beyond the hash
> Add specific version numbers

- core/build.gradle
- material-color-utilities/build.gradle
- material-color-utilities/src/main/java/dynamiccolor/DynamicColor.java
- material-color-utilities/src/main/java/dynamiccolor/MaterialDynamicColors.java
- sample/build.gradle
- ui/build.gradle
* update material colors code to 27th April
* bump lib dependencies
> Maintenance 0.9.0

- sample/src/main/java/com/nextcloud/android/common/sample/MainActivity.kt
- sample/src/main/res/layout/activity_main.xml
- sample/src/main/res/values/dimens.xml
- sample/src/main/res/values/strings.xml
- ui/src/main/java/com/nextcloud/android/common/ui/theme/utils/MaterialViewThemeUtils.kt
> Add theming for filter chips

- ui/src/main/java/com/nextcloud/android/common/ui/theme/utils/MaterialViewThemeUtils.kt
> fix filter chip unselected color

- ui/src/main/java/com/nextcloud/android/common/ui/theme/utils/AndroidViewThemeUtils.kt
Fixes #145 in notes app for me
> Fix spanText IOOBException

- material-color-utilities/src/main/java/dynamiccolor/MaterialDynamicColors.java
- material-color-utilities/src/main/java/hct/Cam16.java
> Update to 20231012 code base

- .github/workflows/assemble.yml
- .github/workflows/check.yml
- build.gradle
- core/build.gradle
- core/src/main/AndroidManifest.xml
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- jitpack.yml
- material-color-utilities/build.gradle
- sample/build.gradle
- ui/build.gradle
- ui/src/main/AndroidManifest.xml
* Bump AGP
* Update module definition style
* Bump Java to 17
> Build(deps): Bump com.android.tools.build:gradle from 7.4.0 to 8.1.4

- ui/src/main/java/com/nextcloud/android/common/ui/theme/utils/MaterialViewThemeUtils.kt
Refs: https://m3.material.io/components/floating-action-button/specs
> feat(ui): Theme secondary FAB

- renovate.json
> Add tags and define schedule for renovate

- gradle/wrapper/gradle-wrapper.properties
> Revert back to gradle 8.6

- .github/workflows/reuse.yml
- .reuse/dep5
- REUSE.toml
Automated update of the reuse.yml workflow from https://github.com/nextcloud/.github
> chore(CI): Updating reuse.yml workflow from template

- .github/workflows/autoApproveSync.yml
[skip-ci]
Signed-off-by: Joas Schilling <coding@schilljs.com>
> ci: Update workflows

- ui/build.gradle
> Bump to SDK35

- material-color-utilities/src/main/java/dynamiccolor/MaterialDynamicColors.java
...sync from library implementation
> Add an API that returns all dynamic color tokens in Java.
